### ISSUE TITLE
No such host when using separate docker-compose up

### ISSUE THREAD

**Issue by sholtomaud** [tgross/workshop-autopilot#24]
I tried splitting consul and nginx out from the rest of the app to simulate adding a new microservice. I would 
run two different ```docker-compose up``` commands one with  consul and nginx, and the other for the sales and customers services. 

however I get this error for the sales and customers services containers.

2016/11/24 06:51:07 Failed to query customers: Get http://consul:8500/v1/health/service/customers?passing=1: dial tcp: lookup consul on 8.8.8.8:53: no such host [<nil>]

**Comment by tgross** [comment]
> I tried splitting consul and nginx out from the rest of the app to simulate adding a new microservice

What's your new configuration look like? The error message you're getting suggests that you're missing a link between containers.

**Comment by sholtomaud** [comment]
So I now have 3 configs. Why? Because I was trying to emulate the [nginxinc consul demo](https://github.com/nginxinc/NGINX-Demos/tree/master/consul-template-demo), which shows "Dynamic Reconfiguration of Upstream servers". The assumption was that the self-aware autopilotpattern would be able to do Dynamic Reconfiguration in the same way. As soon as you run ```docker-compose up``` on a separate microservice registrator registers it. 

The configs I tried with autopliot is below, one for infrastructure, one for sales microservice, and one for the customers microservice. 

### infrastructure.yml
```yaml
# Nginx as a load-balancing tier and reverse proxy
nginx:
    image: autopilotpattern/workshop-nginx
    mem_limit: 128m
    ports:
      - 80
    links:
      - consul:consul
    restart: always
    command: >
      /bin/containerpilot
      -config file:///etc/containerpilot/containerpilot.json
      nginx -g "daemon off;"

# service discovery tier
consul:
    image: progrium/consul:latest
    command: -server -bootstrap -ui-dir /ui
    restart: always
    mem_limit: 128m
    labels:
      - triton.cns.services=consul
    ports:
      - 8500
    dns:
      - 127.0.0.1
```

### sales.yml
```yaml
# the sales microservice
sales:
    image: autopilotpattern/workshop-sales
    # links:
    #   - consul
    command: -ip=10.0.2.15 consul://consul:8500
    mem_limit: 128m
    ports:
      - 3000
    # environment:
    #   - MYSQL_DB=
    #   - MYSQL_USER=
    #   - MYSQL_PASSWORD=
    restart: always
```

### customers.yml
```yaml
# the customers microservice
customers:
    image: autopilotpattern/workshop-customers
    command: -ip=10.0.2.15 consul://consul:8500
    # links:
    #   - consul
    mem_limit: 128m
    ports:
      - 4000
    restart: always
```
